ECommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('account/', include('account.urls')),
    path('', include('backend.urls')),
    path('eadmin/', include('AdminPanel.urls')),
    path('search/', include('search.url')),
    path('coupons', include('coupons.urls', namespace='coupons')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# superUser Name: pustak
# password : pustak123

cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns=[
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:book_id>',views.cart_add,name='cart_add'),
    path('remove/<int:book_id>',views.cart_remove,name='cart_remove')
]

coupons/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply')
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create')

]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
from backend.models import Book


class CartAddBookForm(forms.Form):
    update=forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)

    def __init__(self,*args,**kwargs):
        id=kwargs.pop("id")
        super(CartAddBookForm,self).__init__(*args,**kwargs)
        self.fields['quantity']=forms.TypedChoiceField(choices=[(i,str(i)) for i in range(1,Book.objects.get(id=id).stock+1)],coerce=int)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from backend.models import Book
from .cart import Cart
from .forms import CartAddBookForm
from coupons.forms import CouponApplyForm


@require_POST
def cart_add(request, book_id):
    cart = Cart(request)

    book = get_object_or_404(Book, id=book_id)
    form = CartAddBookForm(request.POST, id=book_id)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(book=book, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, book_id):
    cart = Cart(request)
    book = get_object_or_404(Book, id=book_id)
    cart.remove(book)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddBookForm(id=item['book'].id,
                                                       initial={'quantity': item['quantity'], 'update': True})
    coupon_apply_form = CouponApplyForm()
    return render(request, 'cart/detail.html', {'cart': cart,
                                                'coupon_apply_form': coupon_apply_form})

templates/cart/detail.html
{% extends 'index.html' %}

{% load static %}
    <link href="{% static 'css/detail_view.css' %}">

{% block content %}
<div class="container">
    <div class="row" style="margin-top: 8%">
        <h2>Your Shopping Cart </h2>
    <h4>
        <span class="badge badge-secondary pull-right">
            {% with totail_items=cart|length %}
            {% if cart|length > 0 %}
            Cart
            <a href="{% url "cart:cart_detail" %}" style="color:#ffffff">
                {{ totail_items }} item {{ totail_items|pluralize }}, Rs. {{ cart.get_total_price }}
            </a>
            {% else %}
            Your cart is empty
            {% endif %}
        {% endwith %}
        </span>
        </h4>
    <table class="table table-striped table-hover table-responsive-sm">
        <thead style="background-color: #5AC8FA">
        <tr>
                        <th>Image</th>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Remove</th>
                        <th>Unit Price</th>
                        <th>Total Price</th>

        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
        {% with book=item.book %}
        <tr>
            <td>
                <a href="{{ book.get_absolute_url }}">
                    <img src="{% if book.image %} {{ book.image.url }} {% else %} {% static 'image/1.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">

                </a>
            </td>
            <td>
                 {{ book.title }}

            </td>
            <td>
                <form action="{% url "cart:cart_add" book.id %}" method="post">
                    {%csrf_token %}
                    {% include 'Admin Panel/form_base_admin.html' with form=item.update_quantity_form%}

                    {{ item.update_quantity_form.update }}
                    <input type="submit" value="Update" class="btn btn-sm mdb-color">
                </form>
            </td>
        <td>
            <a href="{% url 'cart:cart_remove' book.id %}" style="color: #0b51c5">Remove</a>
        </td>
            <td>Rs {{ item.price }}</td>
            <td>Rs {{ item.total_price }}</td>
        </tr>
        {% endwith %}
        {% endfor %}
        {% if cart.coupon %}
            <tr style="...">
                <td><b>Subtotal</b></td>
                <td colspan="4"></td>
                <td><b> Rs. {{ cart.get_total_price }}</b></td>
            </tr>
            <tr>
                <td>
                    "{{ cart.coupon.code }}" coupon
                    ({{ cart.coupon.discount }} % off)
                </td>
                <td colspan="4"></td>
                <td>- Rs.{{ cart.get_discount|floatformat:"2" }}</td>
            </tr>
        {% endif %}
            <tr style="background-color: #5AC8FA">
            <td><b>Total</b></td>
            <td colspan="4"></td>
            <td><b>Rs {{ cart.get_total_price_after_discount }}</b></td>
        </tr>
        </tbody>
    </table>
    <p>Apply a Coupon:</p>
    <form action="{% url "coupons:apply" %}" method="post">
            {{ coupon_apply_form }}
            <input type="submit" value="Apply">
        {% csrf_token %}
    </form>

        <p class="text-right">
        <a href="{% url 'index' %}" class="btn btn-default">Continue Shopping</a>
        {% if cart|length > 0 %}
        <a href="{% url 'orders:order_create' %}" class="btn btn-primary">Checkout</a>
        {% else %}
            You must fill your cart in order to Buy items.
        {% endif %}
    </p>
    </div>
</div>
{% endblock %}